DATASETS:
  TRAIN:
    # H36M-TRAIN:
    #   WEIGHT: 0.5
    COCO-TRAIN:
      WEIGHT: 0.8
    MPI-INF-TRAIN:
      WEIGHT: 0.2
  VAL:
    # H36M-VAL-P2:
    #   WEIGHT: 0.5
    COCO-VAL:
      WEIGHT: 1.0
SMPL:
  MODEL_PATH: data/smpl
  GENDER: neutral
  NUM_BODY_JOINTS: 23
  JOINT_REGRESSOR_EXTRA: data/SMPL_to_J19.pkl
  MEAN_PARAMS: data/smpl_mean_params.npz
TRAIN:
  LR: 1e-4
  BATCH_SIZE: 128
  BATCH_SIZE_VAL: 64
  NUM_WORKERS: 8
  TOTAL_STEPS: 100000
  LOG_FREQ: 10000
  CHECKPOINT_FREQ: 10000
  NUM_TRAIN_SAMPLES: 1
  NUM_VAL_SAMPLES: 4

  # ONLY for shortcut model training
  SELF_CONSISTENCY_RATIO: 0.25
  FM_WEIGHT: 1.0
  SC_WEIGHT: 0.0
  # =================================

MODEL:
  IMG_SIZE: 224
  USE_BETAS: FALSE
  BETAS_STATS: data/stats/betas_stats_eft_fits.npz
  DIFFUSION_PROCESS:
    TIMESTEPS_SHORTCUT: 256
    BETA_SCHEDULE: cosine
  DENOISING_MODEL:
    IMG_FEATS: pare
    POSE_DIM: 144
    SHAPE_DIM: 10
    NUM_BLOCKS_POSE: 3
    NUM_BLOCKS_SHAPE: 2
    HIDDEN_LAYER_DIM: 1024
    OBJECTIVE: pred_noise
    USE_SHORTCUT: True
    USE_GUIDANCE: True
    LOSS_TYPE: l2
GUIDANCE:
  OPTIM_ITERS_SHORTCUT: 1
  SAMPLE_START_SHORTCUT: 32
  DDIM_STEP_SIZE_SHORTCUT: 8
  GRADIENT_SCALE_SHORTCUT: 0.5

  W_KP2D: 0.003
  W_MULTIVIEW: 0.005
  W_SMOOTH: 30
  USE_HIPS: FALSE
EXTRA:
  PELVIS_IND: 39
  FOCAL_LENGTH: 5000
  LOAD_IMG_FEATS: None
  LOAD_PREDICTIONS: hmr2
